### ISSUE TITLE
Access to context (peer of request in Alexa payload)

### ISSUE THREAD

**Issue by tjaffri** [cameronhunter/alexa-annotations#30]
Per #22 it is documented that the second parameter for each invocation is the request object. This is useful to get information other than slots out of the request.

However, there are cases where you need other information in the Alexa payload that is not part of the request object, but rather is a peer of the request object. See [this blog post](https://developer.amazon.com/public/community/post/Tx1DSINBM8LUNHY/New-Alexa-Skills-Kit-ASK-Feature-Audio-Streaming-in-Alexa-Skills) about Audio Skills and especially look at the `context` field of the request i.e.:

```json
{
  "version": "string",
  "context": {
    "System": {
      "application": {},
      "user": {},
      "device": {}
    }
  },
  "request": {
    "type": "AudioPlayer.PlaybackStarted",
    "requestId": "string",
    "timestamp": "string",
    "token": "string",
    "offsetInMilliseconds": 0,
    "locale": "string"
  }
}
```

This is similar to `sessionAttributes` which is already addressed but is different in that this is fixed information that spans across all sessions. It includes stuff like the user and device ID etc.

There is a need to access the data in `context` e.g. if you need to identify the user making the request (not all requests have the session object included, e.g. Audio events do not have this)

How about adding context as the _third_ parameter (after request) so people who need to access this information can access it without breaking anyone who is currently not using it?

@cameronhunter: I can send a PR if you agree.

**Comment by cameronhunter** [comment]
Hi Taqi,

I'm trying to migrate all of the `alexa-*` packages into a single monorepo for easier development. Check out the [alexa monorepo](https://github.com/cameronhunter/alexa).

In the most recent version of `alexa-annotations` (developed in the monorepo) the entire event is passed to the annotated function instead of separating out the request object. This was better for smart home skills and isn't too much of an inconvenience for custom skills. It's available in `v8.0.2` and documentation has been updated.
